{% set name = "ktop" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  skip: true  # [py2k]

requirements:
  build:
    - python
    - pip
  run:
    - ipywidgets
    - python

test:
  imports:
    - ktop

about:
  home: https://github.com/deathbeds/ktop
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Use Jupyter Notebooks and Kernels as Widgets
